services:
  roll-tg-bot:
    container_name: roll-tg-bot
    image: ghcr.io/akorzunin/ip-gacha-roll-tg-bot:${IMAGE_TAG:-latest}
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: src-bot/Dockerfile
      target: final
    environment:
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      RUST_LOG: info
      ROUTER_PASS: ${ROUTER_PASS}
      AUTHORIZED_BOT_USERS: ${AUTHORIZED_BOT_USERS}
      NAT_CHECK_INTERVAL_SECS: ${NAT_CHECK_INTERVAL_SECS:-}
      NAT_FIX_MAX_ATTEMPTS: ${NAT_FIX_MAX_ATTEMPTS:-3}
      NAT_FIX_WAIT_SECS: ${NAT_FIX_WAIT_SECS:-10}
      DUCKDNS_UI_URL: ${DUCKDNS_UI_URL:-http://192.168.1.58:3000}
      TELOXIDE_PROXY: ${HTTP_PROXY:-}
      NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1}
    ports:
      - ${PORT:-8000}:8000
