- name: Deploy ip-gacha-roll-tg-bot
  hosts: all
  become: false
  vars:
    project_dir: "~/deploy/ip-gacha-roll-tg-bot"

  tasks:
    - name: Create project directory
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"

    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ project_dir }}/{{ item }}"
        mode: "0755"
      loop:
        - compose.yaml

    - name: Pull new frontend image
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
      register: out
      changed_when: out.rc != 0

    - name: Deploy new image
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
        PORT: "{{ PORT }}"
        TELOXIDE_TOKEN: "{{ TELOXIDE_TOKEN }}"
        ROUTER_PASS: "{{ ROUTER_PASS }}"
        AUTHORIZED_BOT_USERS: "{{ AUTHORIZED_BOT_USERS }}"
      register: out
      changed_when: out.rc != 0
